'use client';
import {useCallback,useEffect,useRef,useState} from 'react';
import {AssetKey,keys,importAssets,clearAssets,resetAssetUrls,getAssetUrl} from '../lib/assetStorage';
type Role='caller'|'client';type Meal='BREAKFAST'|'LUNCH'|'DINNER'|'SNACK';
type Call={id:string,meal:Meal,created:number};type Response={name:string,minutes:number,device:string};type Log={id:number,kind:string,detail:string,created:number};
type State={call:Call|null,responses:Response[],replyUntil:number,testId:number};type AdminState={count:number,logs:Log[]};type AndroidBridge={registerDevice?:(family:string,device:string,name:string)=>void;onFeedback?:(minutes:number)=>void;dismissAlarm?:()=>void};
const labels:Record<Meal,string>={BREAKFAST:'Frühstück',LUNCH:'Mittagessen',DINNER:'Abendessen',SNACK:'Snack'};
const icons:Record<Meal,AssetKey>={BREAKFAST:'breakfast-icon',LUNCH:'lunch-icon',DINNER:'dinner-icon',SNACK:'snack-icon'};
const meals:Meal[]=['BREAKFAST','LUNCH','DINNER','SNACK'];
const empty:State={call:null,responses:[],replyUntil:0,testId:0};
const time=(n:number)=>new Date(n).toLocaleTimeString('de-DE',{hour:'2-digit',minute:'2-digit'});
export function mealAt(date=new Date()):Meal{const h=date.getHours();return h>=5&&h<11?'BREAKFAST':h>=11&&h<15?'LUNCH':h>=17&&h<20?'DINNER':'SNACK'}
function deviceId(){if(typeof crypto!=='undefined'&&typeof crypto.randomUUID==='function')return crypto.randomUUID();const bytes=new Uint8Array(16);if(typeof crypto!=='undefined'&&typeof crypto.getRandomValues==='function')crypto.getRandomValues(bytes);else for(let i=0;i<bytes.length;i++)bytes[i]=Math.floor(Math.random()*256);return [...bytes].map(x=>x.toString(16).padStart(2,'0')).join('')}
async function familyId(pin:string){if(!crypto?.subtle)throw new Error('Bitte FoodCall über die sichere HTTPS-Adresse öffnen.');const digest=await crypto.subtle.digest('SHA-256',new TextEncoder().encode('FoodCall family v1:'+pin));return [...new Uint8Array(digest)].map(x=>x.toString(16).padStart(2,'0')).join('')}
async function api(path:string,payload:object):Promise<{id:string,created:number,ok?:boolean}>{const r=await fetch('/api/'+path,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});const j=await r.json() as {id:string,created:number,error?:string};if(!r.ok)throw new Error(j.error||'Verbindung fehlgeschlagen');return j}
export default function FoodCall({role}:{role:Role}){
 const [ready,setReady]=useState(false),[urls,setUrls]=useState<Record<string,string>>({}),[family,setFamily]=useState(''),[pin,setPin]=useState(''),[name,setName]=useState(''),[view,setView]=useState<'main'|'menu'|'admin'|'settings'|'reminder'>('main');
 const [draftName,setDraftName]=useState(''),[confirmLogout,setConfirmLogout]=useState(false),[adminPassword,setAdminPassword]=useState(''),[adminAuthed,setAdminAuthed]=useState(false),[adminData,setAdminData]=useState<AdminState>({count:0,logs:[]});
 const [data,setData]=useState<State>(empty),[error,setError]=useState(''),[message,setMessage]=useState(''),[incoming,setIncoming]=useState<Call|null>(null),[answered,setAnswered]=useState(false),[seen,setSeen]=useState(''),[reminderAt,setReminderAt]=useState(0);
 const [importStatus,setImportStatus]=useState('');const lastTest=useRef(0),boot=useRef(false),device=useRef('');
 const loadUrls=useCallback(async()=>{const pairs=await Promise.all(keys.map(async k=>[k,await getAssetUrl(k)] as const));setUrls(Object.fromEntries(pairs))},[]);
 useEffect(()=>{if(boot.current)return;boot.current=true;device.current=localStorage.getItem('fc-device')||deviceId();localStorage.setItem('fc-device',device.current);setFamily(localStorage.getItem('fc-family-'+role)||'');setName(localStorage.getItem('fc-name')||'');const params=new URLSearchParams(window.location.search);if(params.get('nativeAlarm')==='1')localStorage.removeItem('fc-seen');if(params.get('nativeReminder')==='1')setView('reminder');loadUrls().catch(()=>{}).finally(()=>setReady(true));if('serviceWorker'in navigator)navigator.serviceWorker.register('/service-worker.js').catch(()=>{})},[role,loadUrls]);
 const refresh=useCallback(async()=>{if(!family)return;try{const res=await fetch('/api/state?family='+family,{cache:'no-store'});const j=await res.json() as State & {error?:string};if(!res.ok)throw new Error(j.error||'Verbindung fehlgeschlagen');setData(j);setError('');if(role==='client'){
 const latest=j.call as Call|null;if(latest&&latest.id!==seen&&latest.created>Date.now()-86400000){setIncoming(latest);setAnswered(false);setSeen(latest.id);localStorage.setItem('fc-seen',latest.id);if('Notification'in window&&Notification.permission==='granted')new Notification('Food Call',{body:`${labels[latest.meal]} ist fertig`})}
 if(j.testId>lastTest.current){if(lastTest.current>0)setMessage('FoodCall Verbindung funktioniert');lastTest.current=j.testId}
 }}catch(e){setError(e instanceof Error?e.message:'Verbindung fehlgeschlagen')}},[family,role,seen]);
 useEffect(()=>{setSeen(localStorage.getItem('fc-seen')||'')},[]);
 useEffect(()=>{if(!family)return;refresh();const id=setInterval(refresh,2500);return()=>clearInterval(id)},[family,refresh]);
 useEffect(()=>{if(!family||role!=='client'||!name)return;const hello=()=>api('hello',{family,device:device.current,name}).catch(()=>{});hello();const id=setInterval(hello,12000);return()=>clearInterval(id)},[family,role,name]);
 useEffect(()=>{if(!family||role!=='client'||!name||!device.current)return;const bridge=(window as Window & {FoodCallAndroid?:AndroidBridge}).FoodCallAndroid;bridge?.registerDevice?.(family,device.current,name)},[family,role,name]);
 useEffect(()=>{if(!reminderAt)return;const id=setInterval(()=>{if(Date.now()>=reminderAt){setView('reminder');setReminderAt(0);if('Notification'in window&&Notification.permission==='granted')new Notification('Food Call',{body:'Zeit fürs Essen!'})}},500);return()=>clearInterval(id)},[reminderAt]);
 useEffect(()=>{if(view!=='reminder')return;const id=setTimeout(()=>{setView('main');setIncoming(null)},120000);return()=>clearTimeout(id)},[view]);
 async function setup(e:React.FormEvent){e.preventDefault();if(!/^[0-9]{6,}$/.test(pin)){setError('Bitte mindestens 6 Ziffern für die Familien-PIN verwenden.');return}if(role==='client'&&!name.trim()){setError('Bitte deinen Namen eingeben.');return}try{const id=await familyId(pin);localStorage.setItem('fc-family-'+role,id);if(role==='client')localStorage.setItem('fc-name',name.trim());setFamily(id);setPin('');setError('');if('Notification'in window&&Notification.permission==='default')Notification.requestPermission().catch(()=>{})}catch(e){setError(e instanceof Error?e.message:'PIN konnte nicht gespeichert werden')}}
 async function send(meal:Meal){try{await api('call',{family,meal});setMessage('');setView('main');await refresh()}catch(e){setError(String(e))}}
 useEffect(()=>{if(role!=='caller'||!family)return;const context=(document as Document & {modelContext?:{registerTool:(tool:object,options:{signal:AbortSignal})=>void|Promise<void>}}).modelContext;if(!context?.registerTool)return;const controller=new AbortController();Promise.resolve(context.registerTool({name:'send_food_call',title:'Essen rufen',description:'Sende einen Essensruf an die verbundenen Clients der eingerichteten Familie.',inputSchema:{type:'object',properties:{meal:{type:'string',enum:['BREAKFAST','LUNCH','DINNER','SNACK']}},required:['meal'],additionalProperties:false},annotations:{readOnlyHint:false},execute:async(input:unknown)=>{const meal=(input as {meal?:string})?.meal;if(!meals.includes(meal as Meal))throw new Error('Ungültiger Essenstyp');const result=await api('call',{family,meal});await refresh();return {callId:result.id,meal}}},{signal:controller.signal})).catch(()=>{});return()=>controller.abort()},[role,family,refresh]);
 async function respond(minutes:number){if(!incoming)return;try{await api('respond',{family,callId:incoming.id,device:device.current,name,minutes});(window as Window & {FoodCallAndroid?:AndroidBridge}).FoodCallAndroid?.onFeedback?.(minutes);setAnswered(true);const when=Date.now()+minutes*60000;setReminderAt(when);localStorage.setItem('fc-reminder',JSON.stringify({when,call:incoming}));setMessage(minutes===0?'Gemeldet – Erinnerung erscheint jetzt':`Gemeldet – Erinnerung in ${minutes} Min`);setTimeout(()=>setMessage(''),4000)}catch(e){setError(String(e))}}
 useEffect(()=>{try{const saved=JSON.parse(localStorage.getItem('fc-reminder')||'null');if(saved?.when&&saved.call){if(saved.when>Date.now()-120000){setReminderAt(saved.when);setIncoming(saved.call);setAnswered(true)}}}catch{}},[]);
 async function pick(files:FileList|null){if(!files)return;try{const r=await importAssets(files);await loadUrls();setImportStatus(`${r.found.length} Bild${r.found.length===1?'':'er'} gespeichert. Nicht ausgewählte Bilder bleiben erhalten.`);setError('')}catch{setError('Bilder konnten nicht gespeichert werden')}}
 async function restoreImages(){try{await clearAssets();resetAssetUrls();await loadUrls();setImportStatus('Mitgelieferte Bilder wiederhergestellt.');setError('')}catch{setError('Bilder konnten nicht zurückgesetzt werden')}}
 const loadAdmin=useCallback(async()=>{const r=await fetch('/api/admin/state?family='+family,{cache:'no-store'});if(r.status===401){setAdminAuthed(false);return}if(!r.ok)throw new Error('Admin-Daten nicht verfügbar');setAdminData(await r.json() as AdminState)},[family]);
 useEffect(()=>{if(view!=='admin'||!adminAuthed)return;loadAdmin().catch(()=>{});const id=setInterval(()=>loadAdmin().catch(()=>{}),5000);return()=>clearInterval(id)},[view,adminAuthed,loadAdmin]);
 async function openAdmin(){setError('');setAdminPassword('');setView('admin');try{const r=await fetch('/api/admin/status',{cache:'no-store'});setAdminAuthed((await r.json() as {authenticated:boolean}).authenticated)}catch{setAdminAuthed(false)}}
 async function signIn(e:React.FormEvent){e.preventDefault();try{await api('admin/login',{password:adminPassword});setAdminPassword('');setAdminAuthed(true);setError('')}catch(e){setError(e instanceof Error?e.message:'Anmeldung fehlgeschlagen')}}
 function saveName(e:React.FormEvent){e.preventDefault();const next=draftName.trim();if(!next){setError('Bitte einen Namen eingeben.');return}localStorage.setItem('fc-name',next);setName(next);setError('');setMessage('Name gespeichert');setView('main')}
 function logout(){localStorage.removeItem('fc-family-client');setFamily('');setIncoming(null);setConfirmLogout(false);setView('main')}
 const img=(key:AssetKey)=>urls[key]||'/assets/'+({logo:'logo','client-paper-bg':'paper','client-lights-bg':'lights','caller-wood-bg':'wood','breakfast-icon':'breakfast','lunch-icon':'lunch','dinner-icon':'dinner','snack-icon':'snack','dev-options-icon':'dev'} as Record<AssetKey,string>)[key]+'.png';
 if(!ready)return <div className="loading">Food Call</div>;
 if(!family)return <main className={'screen '+(role==='caller'?'wood':'paper')} style={{backgroundImage:`url("${img(role==='caller'?'caller-wood-bg':'client-paper-bg')}")`}}><form className="pin-form" onSubmit={setup}><img className="brand-logo" src={img('logo')} alt="FoodCall Logo"/><h1>Food Call</h1><span>{role==='client'?'Client':'Caller'}</span><label>Familien-PIN<input value={pin} onChange={e=>setPin(e.target.value.replace(/[^0-9]/g,''))} type="password" inputMode="numeric" pattern="[0-9]*" autoComplete="new-password" placeholder={role==='caller'?'PIN festlegen':'PIN eingeben'} required/></label>{role==='client'&&<label>Name<input value={name} onChange={e=>setName(e.target.value)} maxLength={40} placeholder="Dein Name" required/></label>}<button className="action" type="submit">{role==='caller'?'PIN speichern':'Verbinden'}</button><p className="form-note">Auf allen Geräten dieselbe PIN verwenden.</p>{error&&<p className="error">{error}</p>}</form></main>;
 const bg=role==='caller'?'caller-wood-bg':view==='reminder'||incoming?'client-lights-bg':'client-paper-bg';
 return <main className={'screen '+(role==='caller'?'wood':incoming||view==='reminder'?'lights':'paper')} style={{backgroundImage:`url("${img(bg)}")`}}>
 {view==='reminder'?<div className="reminder"><div className="brand compact"><img src={img('logo')} alt=""/><h1>Food Call<small>Client</small></h1></div><img className="reminder-logo" src={img('logo')} alt="FoodCall"/><strong>{incoming?labels[incoming.meal]:'Essen'}</strong><button onClick={()=>{(window as Window & {FoodCallAndroid?:AndroidBridge}).FoodCallAndroid?.dismissAlarm?.();setView('main');setIncoming(null);localStorage.removeItem('fc-reminder')}}>unlock</button></div>:
 <><header className="brand"><div className="brand-circle"><img src={img('logo')} alt="FoodCall Logo"/></div><h1>Food Call{role==='client'&&<small>Client</small>}</h1></header>
 {role==='caller'?view==='admin'?null:<><div className="caller-center"><button className="call-button" onClick={()=>send(mealAt())}>ESSEN<br/>RUFEN</button>{data.call&&data.replyUntil>Date.now()&&<section className="reply-panel"><h2>Rückmeldungen</h2><p className="sent">{labels[data.call.meal]} · {time(data.call.created)}</p>{data.responses.length?data.responses.map(r=><p key={r.device}><strong>{r.name}</strong><span>{r.minutes===0?'Sofort':`${r.minutes} min`}</span></p>):<p>Warte auf Antworten …</p>}</section>}</div><button className="menu-toggle" aria-label="Menü öffnen" onClick={()=>{setMessage('');setView('menu')}}><span>☰</span></button>{view==='menu'&&<div className="menu-overlay"><button className="menu-close" onClick={()=>{setMessage('');setView('main')}} aria-label="Menü schließen">×</button><h2>Essen auswählen</h2>{meals.map(m=><button key={m} className="menu-item" onClick={()=>send(m)}><img src={img(icons[m])} alt=""/>{labels[m]}</button>)}<button className="menu-item" onClick={openAdmin}><img src={img('dev-options-icon')} alt=""/>Admin-Panel</button></div>}</>:<div className="client-center">{incoming?<><h2>{labels[incoming.meal]}<br/><span>ist fertig</span></h2>{answered&&reminderAt>0?<p className="client-status">Danke! Deine Erinnerung ist geplant.</p>:null}{!answered&&<button className="respond-main" onClick={()=>setAnswered(true)}>MELDEN</button>}{answered&&reminderAt===0&&<div className="choices">{[0,1,5].map(n=><button key={n} onClick={()=>respond(n)}>{n===0?'JETZT':`${n} MIN`}</button>)}</div>}{answered&&reminderAt>0&&<button className="text-button" onClick={()=>{setIncoming(null);setReminderAt(0);localStorage.removeItem('fc-reminder')}}>Zurück zu Bereit</button>}</>:<><h2>Bereit</h2><p>Letzter Call:<br/><strong>{data.call?time(data.call.created):'--'}</strong></p></>}</div>}
 {role==='client'&&view==='main'&&<button className="client-settings" aria-label="Client-Einstellungen" onClick={()=>{setDraftName(name);setConfirmLogout(false);setMessage('');setView('settings')}}>⚙</button>}
 {view==='settings'&&role==='client'&&<div className="settings-overlay"><section className="settings-card"><button className="back" onClick={()=>{setConfirmLogout(false);setView('main')}}>← Zurück</button><h2>Einstellungen</h2><form onSubmit={saveName}><label>Dein Name<input value={draftName} maxLength={40} onChange={e=>setDraftName(e.target.value)}/></label><button className="action" type="submit">Name speichern</button></form><button className="setting" onClick={openAdmin}>Admin-Panel öffnen</button>{confirmLogout?<div className="logout-confirm" role="group" aria-label="Abmeldung bestätigen"><p>Wirklich abmelden?</p><div><button className="setting" onClick={()=>setConfirmLogout(false)}>Abbrechen</button><button className="action" onClick={logout}>Abmelden</button></div></div>:<button className="setting" onClick={()=>setConfirmLogout(true)}>Abmelden …</button>}</section></div>}
 {view==='admin'&&<div className="settings-overlay"><section className="dev admin-card"><button className="back" onClick={()=>{setAdminPassword('');setView(role==='client'?'settings':'main')}}>← Zurück</button><h2>Admin-Panel</h2>{adminAuthed?<>{role==='client'&&<div className="admin-call"><button className="admin-call-main" onClick={()=>send(mealAt())}>ESSEN RUFEN <span>({labels[mealAt()]})</span></button><p>Oder Essen auswählen:</p><div className="admin-meals">{meals.map(m=><button key={m} onClick={()=>send(m)}><img src={img(icons[m])} alt=""/>{labels[m]}</button>)}</div></div>}<div className="dev-count"><strong>{adminData.count}</strong><span>Verbundene Geräte</span></div><button className="action" onClick={()=>api('test',{family}).then(()=>setMessage('Test gesendet')).catch(e=>setError(String(e)))}>Alle Geräte testen</button><h3>Logs</h3><div className="logs">{adminData.logs.length?adminData.logs.map(l=><p key={l.id}><time>{new Date(l.created).toLocaleTimeString('de-DE')}</time> {l.detail}</p>):<p>Noch keine Einträge</p>}</div>{role==='caller'&&<><button className="setting" onClick={()=>{localStorage.removeItem('fc-family-caller');setFamily('');setView('main')}}>Familien-PIN ändern</button><label className="setting file">Eigene Bilder auswählen<input type="file" accept="image/png,image/*" multiple onChange={e=>pick(e.target.files)}/></label><button className="setting" onClick={restoreImages}>Mitgelieferte Bilder wiederherstellen</button>{importStatus&&<p role="status">{importStatus}</p>}</>}<button className="setting" onClick={()=>{api('admin/logout',{}).finally(()=>{setAdminAuthed(false);setView(role==='client'?'settings':'main')})}}>Admin abmelden</button></>:<form className="admin-login" onSubmit={signIn}><label>Admin-Passwort<input type="password" value={adminPassword} onChange={e=>setAdminPassword(e.target.value)} autoComplete="current-password" required/></label><button className="action" type="submit">Anmelden</button></form>}</section></div>}
 {error&&<p className="toast error" role="alert">{error}</p>}{message&&<p className="toast" role="status">{message}</p>}</>}
 </main>
}
